#!/bin/bash
# WF 2016-06-03
. jdk8
mvn -U clean install deploy -D skipTests -DaltDeploymentRepository=BITPlan-release-repository::default::scp://q.bitplan.com/srv/repo/releases
# -Dgpg.skip
mvn nexus-staging:release
